server {
    listen 8080;
    server_name localhost;

    root ./www;
    index index.html;

    error_page 404 /Error_pages/404.html;

    location / {
        autoindex off;
        allow_methods GET;
    }
}