server {
	listen 8080;
	server_name localhost;

	root ./www;
	index index.html index.htm;
	client_max_body_size 10000000;
	upload_dir ./upload

	error_page 400 ./Error_pages/400.html;
	error_page 403 ./Error_pages/403.html;
	error_page 405 ./Error_pages/405.html;
	error_page 404 ./Error_pages/404.html;
	error_page 500 ./Error_pages/500.html;

	location / {
		autoindex on;
		allow_methods GET POST DELETE;
	}

	location /upload {
		allow_methods POST DELETE;
		upload_dir ./upload
	}

	location /page {
		# root ./page;
		allow_methods GET;
	}

	location /cgi-bin {
		# root ./cgi-bin;
		allow_methods GET POST;
		cgi_extension .py .php .pl .cgi;
	}

	location /old {
		return 301 /new;
	}

	location /delete {
		# root ./uploads;
		allow_methods DELETE;
	}
}

server {
	listen 8081;
	server_name localhost;

	index index.html index.htm;
	client_max_body_size 10000000;

	error_page 400 ./Error_pages/400.html;
	error_page 404 ./Error_pages/404.html;
	error_page 405 ./Error_pages/405.html;
	error_page 500 ./Error_pages/500.html;

	location / {
		autoindex on;
		allow_methods GET POST;
	}

	location /upload {
		root ./uploads;
		allow_methods POST;
	}

	location /cgi-bin {
		# root ./cgi-bin;
		allow_methods GET POST;
		cgi_extension .py .php .js;
	}

	location /old {
		return 301 /new;
	}

	location /delete {
		# root ./uploads;
		allow_methods DELETE;
	}
}
