server {
	listen 8080;
	server_name localhost;

	index index.html;

	error_page 404 ./Error_pages/404.html;

	location / {
		autoindex off;
		allow_methods GET;
	}
}

server {
	listen 0.0.0.0:4243;
	server_name localhost;

	index index.html;

	error_page 500 ./Error_pages/500.html;

	location / {
		autoindex off;
		allow_methods GET;
	}
}

server {
	listen 8282;
	server_name localhost;

	index index.html;

	error_page 500 ./Error_pages/500.html;

	location / {
		autoindex off;
		allow_methods GET;
	}
}
